web_app/auth_view/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import InputRequired, Length, Email, Optional


class LoginForm(Form):
    """
    Simple Login form
    """

    email = StringField("Email", validators = [InputRequired(), Length(1, 64), Email()])
    password = PasswordField("Passowrd", validators = [InputRequired()])
    remember_me = BooleanField("Keep me logged in")
    submit = SubmitField("Log In")


class SignUpForm(Form):
    """
    Simple Sign-Up form
    """

    name = StringField("Nick Name", validators = [InputRequired(), Length(1, 32)])
    email = StringField("Email", validators = [InputRequired(), Length(1, 64), Email()])
    address = StringField("Address", validators = [Optional(), Length(1, 128)])
    password = PasswordField("Passowrd", validators = [InputRequired(), Length(6, 16)])
    re_password = PasswordField("Retype Password", validators = [InputRequired(), Length(6, 16)])
    submit = SubmitField("Sign Up!")

web_app/__init__.py
import logging
from flask import Flask
from flask_apscheduler import APScheduler
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_moment import Moment
from config import config


VERSION = "0.0.1a"

# Web app's exposed services (package globals)
db = None
apscheduler = None
bootstrap = None
login_manager = None
moment = None
global_config = None

logger = logging.getLogger(__name__)


def create_app(config_name):

    global db, apscheduler, bootstrap, login_manager, moment, global_config

    # Init vanilla Flask app (no dependencies)
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # Externalize app configuration so that other services not necessarily tied to the app can share a single configuration object
    global_config = app.config

    # Add SQL DB dependency
    if app.config.get("SQLALCHEMY_DATABASE_URI") is not None:
        from flask_sqlalchemy import SQLAlchemy
        db = SQLAlchemy(app)
        db.init_app(app)
    else:
        logger.error("SQLALCHEMY_DATABASE_URI is not defined in configuration file. Aborting.")
        raise EnvironmentError(">>> SQL database not configured")

    # Add Bootstrap dependency
    bootstrap = Bootstrap()
    bootstrap.init_app(app)

    # Add APScheduler dependency
    try:
        apscheduler = APScheduler()
        apscheduler.init_app(app)
    except Exception as e:
        logger.warn("APScheduler is (likely) already running <{0}>".format(e))

    # Add Login Manager dependency
    login_manager = LoginManager()
    # This is where the app will route if the user attempts to access an "authenticated only" page
    login_manager.login_view = "auth_view.get_login"
    login_manager.init_app(app)

    # Add Moment library (time formatting) dependency
    moment = Moment()
    moment.init_app(app)

    # Register template engine helper functions
    from utils.time import convert_jira_datetime_to_datetime, format_seconds_to_days
    app.add_template_global(len, name="len")
    app.add_template_global(convert_jira_datetime_to_datetime, name="convert_jira_datetime_to_datetime")
    app.add_template_global(format_seconds_to_days, name="format_seconds_to_days")

    # Register Jira Stats view routes
    from .stats_view import stats_view as stats_blueprint
    app.register_blueprint(stats_blueprint)

    # Register authentication related view routes
    from .auth_view import auth_view as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = "/auth")

    return app

web_app/auth_view/__init__.py
from flask import Blueprint

auth_view = Blueprint("auth_view", __name__)

from . import routes

web_app/auth_view/routes.py
import logging
from flask import render_template, request, url_for, flash, redirect
from flask_login import login_user, logout_user, login_required
from . import auth_view
from .forms import LoginForm, SignUpForm
from services.auth import create_user, fetch_user_by_email, verify_password


logger = logging.getLogger(__name__)


@auth_view.route("/login", methods=["GET"])
def get_login():

    login_form = LoginForm()
    return render_template("auth/login.html", form=login_form)


@auth_view.route("/login", methods=["POST"])
def post_login():

    login_form = LoginForm()

    # Login form fields have NOT passed validation
    if not login_form.validate_on_submit():
        return render_template("auth/login.html", form=login_form)

    # Attempt to fetch the user from the DB by the specified email
    user = fetch_user_by_email(login_form.email.data)

    # If user exists in the database and has specified a valid password, log him / her in
    if user and verify_password(user, login_form.password.data):
        login_user(user, login_form.remember_me.data)
        return redirect(request.args.get("next") or url_for("stats_view.get_issues_being_tracked"))
    # Either user's email or password are invalid
    else:
        flash("Invalid email or password. Please try again.")
        return redirect(url_for(".get_login"))


@auth_view.route("/logout", methods=["GET", "POST"])
@login_required
def get_logout():

    logout_user()
    flash("You have been logged-out")
    return redirect(url_for(".get_login"))


@auth_view.route("/signup", methods=["GET"])
def get_signup():

    signup_form = SignUpForm()
    return render_template("auth/signup.html", signup_form=signup_form)


@auth_view.route("/signup", methods=["POST"])
def post_signup():

    signup_form = SignUpForm()

    # Sign-up form fields have NOT passed validation
    if not signup_form.validate_on_submit():
        return render_template("auth/signup.html", signup_form=signup_form)

    # Email is not already taken (i.e., user exists in the database)
    email_in_use = fetch_user_by_email(signup_form.email.data)

    if email_in_use:
        flash("Email is already taken. Please try a different one.")
    # The two password (passowrd and repeat password) do not match
    elif signup_form.password.data != signup_form.re_password.data:
        flash("The passwords entered do not match. Please try again.")
    # All is good, create the new user
    else:
        create_user(name=signup_form.name.data,
            email=signup_form.email.data,
            password=signup_form.password.data,
            address=signup_form.address.data)
        flash("Thank you, {nick}! Please login.".format(nick=signup_form.name.data))
        logger.info("User {nick} has successfuly registered".format(nick=signup_form.name.data))
        return redirect(url_for(".get_login"))

    return render_template("auth/signup.html", signup_form=signup_form)

web_app/stats_view/__init__.py
from flask import Blueprint

stats_view = Blueprint("stats_view", __name__)

from . import routes

web_app/stats_view/routes.py
from flask import render_template, request, flash, Response
from flask_login import login_required
from services.issues import fetch_all_issues, fetch_all_users, retrieve_issue_from_jira, upsert_issue
from . import stats_view


@stats_view.route("/issues", methods=["GET"])
@stats_view.route("/", methods=["GET"])
@login_required
def get_issues_being_tracked():

    issues = fetch_all_issues()
    return render_template("stats/list_issues.html",issues=issues)


@stats_view.route("/users", methods=["GET"])
@login_required
def get_worklog_reporting_users():

    users = fetch_all_users()
    return render_template("stats/list_users.html",users=users)


@stats_view.route("/issues/add", methods=["POST"])
@login_required
def post_add_issue_for_tracking():

    new_issue = None
    new_issue_id = request.form.get("new_issue_id")
    if new_issue_id:
        jira_issue = retrieve_issue_from_jira(new_issue_id)
        if jira_issue:
            new_issue = upsert_issue(issue_id=new_issue_id, updated=jira_issue.fields.updated, summary=jira_issue.fields.summary,
                                     status=jira_issue.fields.status.name, overall_worklog=jira_issue.fields.aggregatetimespent)

    if new_issue:
        flash("Issue {id} is now being tracked".format(id=new_issue.issue_id))
    else:
        flash("Issue could not be added. Please try again in a little while")

    issues = fetch_all_issues()
    return render_template("stats/list_issues.html",issues=issues)


@stats_view.route("/issues/validate", methods=["POST"])
@login_required
def get_validate_issue_before_adding():

    """
    This function is AJAX invoked by the JQuery Validate plugin used to provide the user with feedback on the
    validity of the issue id being added for tracking.
    :return: plain text "true" or "false", as expected by JQuery's Validate plugin
    """
    new_issue_id = request.form.get("new_issue_id")
    if new_issue_id:
        jira_issue = retrieve_issue_from_jira(new_issue_id)
        if jira_issue:
                return Response("true", mimetype="text/plain")

    return Response("false", mimetype="text/plain")

web_app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    Jira Me! Who worked on which issue? For how long?
{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

<!--
    Navigation bar block. Note the different options available to authenicated users vs. unauthenticated ones.
-->
{% block navbar %}
    <nav class="navbar navbar-default xnavbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Jira Me!</a>
            </div>
            <div>
                {% if current_user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{ url_for('stats_view.get_issues_being_tracked') }}">List By Issue</a></li>
                        <li><a href="{{ url_for('stats_view.get_worklog_reporting_users') }}">List By Reporter</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span>
                                {{ current_user.name }}'s Profile
                            </a>
                            <ul class="dropdown-menu">
                               <li><a href="#">{{ current_user.name }}</a></li>
                               <li><a href="#">Edit...</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ url_for('auth_view.get_logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('auth_view.get_signup') }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="{{ url_for('auth_view.get_login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <!--
            Common flash messages display at the top of the page. Multiple messages will be stacked.
        -->
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        <!--
            The following block needs to be overridden in any template inheriting from this one.
        -->
        {% block page_content %}
            <h2>Default base page content. Override page_content block to customize.</h2>
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}